In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("D:\\Data-Engg-Work\\train.csv", engine="python", on_bad_lines="warn")
print(df.shape)
df.head()

(9800, 18)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [9]:
# Data ka overview
print("Shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isnull().sum())

Shape: (9800, 18)

Column names: ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales']

Data types:
 Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

Missing values:
 Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [10]:
# Issue 1: Date columns fix karo
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

# Issue 2 & 3: Postal Code - pehle missing fill karo, phir string banao
df['Postal Code'] = df['Postal Code'].fillna(0)
df['Postal Code'] = df['Postal Code'].astype(int).astype(str)

# Verify - sab theek hua?
print(df.dtypes)
print("\nMissing values:\n", df.isnull().sum())
print("\nSample dates:", df['Order Date'].head(3).tolist())

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code              object
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
dtype: object

Missing values:
 Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

Sample dates: [Timestamp('2017-11-08 00:00:00'), Timestamp('2017-11-08 00:00:00'), Timestamp('2017-06-12 00:00:00')]

## GROUPBY AND AGGREGATE

In [11]:
# Basic groupby - category wise total sales
category_sales = df.groupby('Category')['Sales'].sum()
print(category_sales)

Category
Furniture          728658.5757
Office Supplies    705422.3340
Technology         827455.8730
Name: Sales, dtype: float64

In [12]:
# Ek saath multiple calculations
category_stats = df.groupby('Category').agg(
    total_sales    = ('Sales', 'sum'),
    avg_sales      = ('Sales', 'mean'),
    order_count    = ('Order ID', 'count'),
    max_sale       = ('Sales', 'max')
).reset_index()

print(category_stats)

          Category  total_sales   avg_sales  order_count   max_sale
0        Furniture  728658.5757  350.653790         2078   4416.174
1  Office Supplies  705422.3340  119.381001         5909   9892.740
2       Technology  827455.8730  456.401474         1813  22638.480

## FILTERING

In [13]:
# Sirf woh categories jinka total sales 800000 se zyada ho
high_sales = category_stats[category_stats['total_sales'] > 800000]
print(high_sales)

     Category  total_sales   avg_sales  order_count  max_sale
2  Technology   827455.873  456.401474         1813  22638.48

In [14]:
# Total sales 500000 se zyada AUR average sale 200 se zyada
filtered = category_stats[
    (category_stats['total_sales'] > 500000) & 
    (category_stats['avg_sales'] > 200)
]
print(filtered)

     Category  total_sales   avg_sales  order_count   max_sale
0   Furniture  728658.5757  350.653790         2078   4416.174
2  Technology  827455.8730  456.401474         1813  22638.480

In [15]:
region_category = df.groupby(['Region', 'Category']).agg(
    total_sales   = ('Sales', 'sum'),
    order_count   = ('Order ID', 'count'),
    avg_sales     = ('Sales', 'mean')
).reset_index()

# Sirf woh combinations jahan orders 100 se zyada hon
region_category = region_category[region_category['order_count'] > 100]

print(region_category)

     Region         Category  total_sales  order_count   avg_sales
0   Central        Furniture  160317.4622          470  341.100983
1   Central  Office Supplies  163590.2430         1399  116.933698
2   Central       Technology  168739.2080          408  413.576490
3      East        Furniture  206461.3880          591  349.342450
4      East  Office Supplies  199940.8110         1667  119.940499
5      East       Technology  263116.5270          527  499.272347
6     South        Furniture  116531.4800          326  357.458528
7     South  Office Supplies  124424.7710          983  126.576573
8     South       Technology  148195.2080          289  512.786187
9      West        Furniture  245348.2455          691  355.062584
10     West  Office Supplies  217466.5090         1860  116.917478
11     West       Technology  247404.9300          589  420.042326

In [16]:
region_category = df.groupby(['Region']).agg(
    total_sales   = ('Sales', 'sum'),
    order_count   = ('Order ID', 'count'),
    avg_sales     = ('Sales', 'mean')
).reset_index()

# Sirf woh combinations jahan orders 100 se zyada hon
region_category = region_category[region_category['order_count'] > 100]

print(region_category)

    Region  total_sales  order_count   avg_sales
0  Central  492646.9132         2277  216.357889
1     East  669518.7260         2785  240.401697
2    South  389151.4590         1598  243.524067
3     West  710219.6845         3140  226.184613

In [17]:
shipmodes=df.groupby(['Segment','Ship Mode']).agg(
    total_sales=('Sales','sum'),
    order_count=('Order ID','count'),
    minimum_sales=('Sales','min')
).reset_index()

print(shipmodes)

        Segment       Ship Mode  total_sales  order_count  minimum_sales
0      Consumer     First Class  158104.9470          755          0.984
1      Consumer        Same Day   57452.2730          312          0.852
2      Consumer    Second Class  230125.5356         1003          1.344
3      Consumer  Standard Class  702377.7754         3031          0.444
4     Corporate     First Class  102580.0539          468          1.188
5     Corporate        Same Day   45121.3230          114          0.556
6     Corporate    Second Class  139045.2908          589          1.188
7     Corporate  Standard Class  401747.4071         1782          0.836
8   Home Office     First Class   84887.2564          278          0.990
9   Home Office        Same Day   22645.4430          112          1.408
10  Home Office    Second Class   80743.3530          310          1.524
11  Home Office  Standard Class  236706.1245         1046          1.408

In [18]:
shipmode=df.groupby(['Segment','Ship Mode']).agg(
    total_sales=('Sales','sum'),
    order_count=('Order ID','count'),
    minimum_sales=('Sales','min'),
    avg_sales= ('Sales', 'mean'),
).reset_index()

shipmodes= shipmode[shipmode['avg_sales'] > 300]
print(shipmodes)

       Segment    Ship Mode  total_sales  order_count  minimum_sales  \
5    Corporate     Same Day   45121.3230          114          0.556
8  Home Office  First Class   84887.2564          278          0.990

    avg_sales
5  395.801079
8  305.349843

## MERGE

In [19]:
#for merge practice another table
# Returns data manually banana
returns_df = pd.DataFrame({
    'Order ID': [
        'CA-2017-152156',
        'US-2016-108966', 
        'CA-2015-138422',
        'CA-2016-139892',
        'CA-2017-143567'
    ],
    'Returned': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes']
})

print(returns_df)

         Order ID Returned
0  CA-2017-152156      Yes
1  US-2016-108966      Yes
2  CA-2015-138422      Yes
3  CA-2016-139892      Yes
4  CA-2017-143567      Yes

In [20]:
# inner join
inner = df.merge(returns_df, on='Order ID', how='inner')
print("Inner merge rows:", inner.shape[0])
print(inner[['Order ID', 'Customer Name', 'Sales', 'Returned']].head())

Inner merge rows: 4
         Order ID   Customer Name     Sales Returned
0  CA-2017-152156     Claire Gute  261.9600      Yes
1  CA-2017-152156     Claire Gute  731.9400      Yes
2  US-2016-108966  Sean O'Donnell  957.5775      Yes
3  US-2016-108966  Sean O'Donnell   22.3680      Yes

In [21]:
#left join
left = df.merge(returns_df, on='Order ID', how='left')
print("Left merge rows:", left.shape[0])

# Returned column mein NaN woh orders hain jo return nahi hue
print("\nReturned value counts:")
print(left['Returned'].value_counts(dropna=False))

Left merge rows: 9800

Returned value counts:
Returned
NaN    9796
Yes       4
Name: count, dtype: int64

In [22]:
not_returned = left[left['Returned'].isna()]
print("Non-returned orders:", not_returned.shape[0])

Non-returned orders: 9796

## Postgre Connection

In [23]:
#pip install psycopg2-binary

In [24]:
from sqlalchemy import create_engine

# Connection banao
#engine = create_engine('postgresql://postgres:yourpassword@localhost:5432/Query_practice')

# Test karo
with engine.connect() as conn:
    print("Connected!")

Connected!

In [25]:
# Seedha SQL query chala ke pandas mein laao
import pandas as pd
df_from_db = pd.read_sql("SELECT * FROM superstore WHERE category = 'Technology'", engine)
print(df_from_db.shape)
df_from_db.head()

(1813, 20)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,order_date_proper,ship_date_proper
0,1923,CA-2017-156685,8/7/2017,10/7/2017,Second Class,SC-20230,Scot Coram,Corporate,United States,Arlington,Texas,76017,Central,TEC-PH-10004345,Technology,Phones,Cisco SPA 502G IP Phone,863.640,2017-07-08,2017-07-10
1,4115,CA-2016-116687,2/5/2016,7/5/2016,Standard Class,NC-18625,Noah Childs,Corporate,United States,Houston,Texas,77095,Central,TEC-PH-10001750,Technology,Phones,Samsung Rugby III,158.376,2016-05-02,2016-05-07
2,4273,US-2018-158505,21/07/2018,21/07/2018,Same Day,SF-20200,Sarah Foster,Consumer,United States,Murray,Utah,84107,West,TEC-PH-10004071,Technology,Phones,PayAnywhere Card Reader,71.928,2018-07-21,2018-07-21
3,4306,CA-2015-162278,26/10/2015,30/10/2015,Second Class,AH-10585,Angele Hood,Consumer,United States,Seattle,Washington,98105,West,TEC-PH-10000526,Technology,Phones,Vtech CS6719,383.960,2015-10-26,2015-10-30
4,8,CA-2015-115812,9/6/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,2015-06-09,2015-06-14

In [26]:
# Jo bhi transformation ki hai, result database mein save karo
region_category.to_sql(
    'region_category_summary',  # nayi table ka naam
    engine,
    if_exists='replace',        # agar table hai to replace karo
    index=False
)
print("Table saved to database!")

Table saved to database!

In [27]:
# Confirm karo table ban gayi
verify = pd.read_sql("SELECT * FROM region_category_summary", engine)
print(verify)

    Region  total_sales  order_count   avg_sales
0  Central  492646.9132         2277  216.357889
1     East  669518.7260         2785  240.401697
2    South  389151.4590         1598  243.524067
3     West  710219.6845         3140  226.184613

## DATA QUALITY CHECKS

In [28]:
def check_data_quality(df, name):
    print(f"\n=== Data Quality Report: {name} ===")
    
    # 1. Shape check
    print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
    
    # 2. Missing values
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) == 0:
        print("Missing values: None - OK")
    else:
        print(f"Missing values:\n{missing} - WARNING")
    
    # 3. Duplicate rows
    dupes = df.duplicated().sum()
    print(f"Duplicate rows: {dupes} - {'OK' if dupes == 0 else 'WARNING'}")
    
    # 4. Negative sales check
    if 'Sales' in df.columns:
        neg = df[df['Sales'] < 0].shape[0]
        print(f"Negative sales: {neg} - {'OK' if neg == 0 else 'WARNING'}")

check_data_quality(df, "Superstore")

=== Data Quality Report: Superstore ===
Rows: 9800, Columns: 18
Missing values: None - OK
Duplicate rows: 0 - OK
Negative sales: 0 - OK

## DATE AND TIME OPERATIONS

In [29]:
# Pehle confirm karo dates properly loaded hain
print(df['Order Date'].dtype)
print(df['Order Date'].head(3))

datetime64[ns]
0   2017-11-08
1   2017-11-08
2   2017-06-12
Name: Order Date, dtype: datetime64[ns]

In [30]:
# Date ke alag alag parts nikalna
df['Order Year']    = df['Order Date'].dt.year
df['Order Month']   = df['Order Date'].dt.month
df['Order Day']     = df['Order Date'].dt.day
df['Order Weekday'] = df['Order Date'].dt.day_name()

print(df[['Order Date', 'Order Year', 'Order Month', 'Order Day', 'Order Weekday']].head(10))

  Order Date  Order Year  Order Month  Order Day Order Weekday
0 2017-11-08        2017           11          8     Wednesday
1 2017-11-08        2017           11          8     Wednesday
2 2017-06-12        2017            6         12        Monday
3 2016-10-11        2016           10         11       Tuesday
4 2016-10-11        2016           10         11       Tuesday
5 2015-06-09        2015            6          9       Tuesday
6 2015-06-09        2015            6          9       Tuesday
7 2015-06-09        2015            6          9       Tuesday
8 2015-06-09        2015            6          9       Tuesday
9 2015-06-09        2015            6          9       Tuesday

In [31]:
# Ship Date - Order Date = kitne din mein deliver hua
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

print(df[['Order Date', 'Ship Date', 'Delivery Days']].head(10))
print("\nAverage delivery days:", df['Delivery Days'].mean().round(2))

  Order Date  Ship Date  Delivery Days
0 2017-11-08 2017-11-11              3
1 2017-11-08 2017-11-11              3
2 2017-06-12 2017-06-16              4
3 2016-10-11 2016-10-18              7
4 2016-10-11 2016-10-18              7
5 2015-06-09 2015-06-14              5
6 2015-06-09 2015-06-14              5
7 2015-06-09 2015-06-14              5
8 2015-06-09 2015-06-14              5
9 2015-06-09 2015-06-14              5

Average delivery days: 3.96

In [32]:
delivery_analysis = df.groupby('Ship Mode').agg(
    avg_delivery_days = ('Delivery Days', 'mean'),
    min_days          = ('Delivery Days', 'min'),
    max_days          = ('Delivery Days', 'max'),
    order_count       = ('Order ID', 'count')
).round(2).reset_index()

print(delivery_analysis)

        Ship Mode  avg_delivery_days  min_days  max_days  order_count
0     First Class               2.18         1         4         1501
1        Same Day               0.04         0         1          538
2    Second Class               3.25         1         5         1902
3  Standard Class               5.01         3         7         5859

## STRING OPERATIONS

In [33]:
# .str. gateway hai strings ka, jaise .dt. tha dates ka
df['Customer Name Upper'] = df['Customer Name'].str.upper()
df['Customer Name Lower'] = df['Customer Name'].str.lower()
df['Customer Name Strip'] = df['Customer Name'].str.strip()

print(df[['Customer Name', 'Customer Name Upper', 'Customer Name Lower']].head(5))

     Customer Name Customer Name Upper Customer Name Lower
0      Claire Gute         CLAIRE GUTE         claire gute
1      Claire Gute         CLAIRE GUTE         claire gute
2  Darrin Van Huff     DARRIN VAN HUFF     darrin van huff
3   Sean O'Donnell      SEAN O'DONNELL      sean o'donnell
4   Sean O'Donnell      SEAN O'DONNELL      sean o'donnell

In [34]:
# Customer Name ko first aur last name mein todna
df[['First Name', 'Last Name']] = df['Customer Name'].str.split(' ', n=1, expand=True)

print(df[['Customer Name', 'First Name', 'Last Name']].head(10))

     Customer Name First Name  Last Name
0      Claire Gute     Claire       Gute
1      Claire Gute     Claire       Gute
2  Darrin Van Huff     Darrin   Van Huff
3   Sean O'Donnell       Sean  O'Donnell
4   Sean O'Donnell       Sean  O'Donnell
5  Brosina Hoffman    Brosina    Hoffman
6  Brosina Hoffman    Brosina    Hoffman
7  Brosina Hoffman    Brosina    Hoffman
8  Brosina Hoffman    Brosina    Hoffman
9  Brosina Hoffman    Brosina    Hoffman

In [35]:
# Product name mein "Phone" wali rows dhoondo
phones = df[df['Product Name'].str.contains('Phone', case=False, na=False)]
print(f"Phone products: {phones.shape[0]}")
print(phones['Product Name'].unique()[:5])

Phone products: 520
['Mitel 5320 IP Phone VoIP phone'
 'Konftel 250 Conference\xa0phone\xa0- Charcoal black'
 'Cisco SPA 501G IP Phone'
 'LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite'
 'AT&T CL83451 4-Handset Telephone']

In [36]:
# Ship Mode mein "Class" word hatao
df['Ship Mode Clean'] = df['Ship Mode'].str.replace(' Class', '', regex=False)
print(df[['Ship Mode', 'Ship Mode Clean']].drop_duplicates())

          Ship Mode Ship Mode Clean
0      Second Class          Second
3    Standard Class        Standard
35      First Class           First
366        Same Day        Same Day

In [37]:
def clean_text_columns(df):
    # Sare text columns ke spaces hatao aur lowercase karo
    text_cols = df.select_dtypes(include='object').columns
    
    for col in text_cols:
        df[col] = df[col].str.strip()
        df[col] = df[col].str.lower()
    
    print(f"Cleaned {len(text_cols)} text columns")
    return df

df = clean_text_columns(df)

Cleaned 21 text columns